<?php
/**
 * @package             jInbound
 * @subpackage          com_jinbound
 **********************************************
 * jInbound
 * Copyright (c) 2013 Anything-Digital.com
 * Copyright (c) 2018 Open Source Training, LLC
 **********************************************
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.n *
 * This header must not be removed. Additional contributions/changes
 * may be added to this header as long as no information is deleted.
 */

defined('JPATH_PLATFORM') or die;

$this->cols = 12;

echo $this->loadTemplate('list');

?>

<script type="text/javascript">
    (function($) {
        $(function() {
            var ids = [];
            // autogenerated list 
            <?php foreach ($this->items as $item) : ?>
            ids.push(<?php echo (int)$item->id; ?>);
            <?php endforeach; ?>
            if (ids.length) {
                $.ajax('../index.php?option=com_jinbound&task=landingpageurl&id[]=' + ids.join('&id[]='), {
                    dataType: 'json',
                    success : function(response) {
                        if (!response) {
                            return;
                        }
                        if (!(response.links && response.links.length)) {
                            if (response.id) {
                                var cell = $('#landingpagelink_' + response.id);
                                if (cell && response.sef) {
                                    cell.append($('<a href="' + response.sef + '" target="_blank" title="<?php echo JText::_('COM_JINBOUND_OPEN_IN_NEW_WINDOW'); ?>"><img src="../media/system/images/weblink.png" /></a>'));
                                }
                            }
                            return;
                        }
                        $.each(response.links, function(i, el) {
                            var cell = $('#landingpagelink_' + el.id);
                            if (cell && el.sef) {
                                cell.append($('<a href="' + el.sef + '" target="_blank" title="<?php echo JText::_('COM_JINBOUND_OPEN_IN_NEW_WINDOW'); ?>"><img src="../media/system/images/weblink.png" /></a>'));
                            }
                        });
                    }
                });
            }
        });
    })(jQuery);
</script>
