<?php
/**
 * @package		JInbound
 * @subpackage	com_jinbound
@ant_copyright_header@
 */

defined('JPATH_PLATFORM') or die;

$this->cols = 9;

echo $this->loadTemplate('list');

?>

<script type="text/javascript">
(function($)
{
	$(function()
	{
		var ids = [];
		// autogenerated list 
<?php foreach ($this->items as $item) : ?>
		ids.push(<?php echo (int) $item->id; ?>);
<?php endforeach; ?>
		if (ids.length)
		{
			$.ajax('../index.php?option=com_jinbound&task=landingpageurl&id[]=' + ids.join('&id[]='), {
				dataType: 'json',
				success: function(response)
				{
					if (!response)
					{
						return;
					}
					if (!(response.links && response.links.length))
					{
						return;
					}
					$.each(response.links, function(idx, el)
					{
						var cell = $('#landingpagelink_' + el.id);
						if (cell && cell.sef)
						{
							cell.append($('<a href="' + el.sef + '" target="_blank" title="<?php echo JText::_('COM_JINBOUND_OPEN_IN_NEW_WINDOW'); ?>"><img src="../media/system/images/weblink.png" /></a>'));
						}
					});
				}
			});
		}
	});
})(jQuery);
</script>
